export default async function handler(request, response) {
  try {
    const { renderPage } = await import('vike/server')
    const { url } = request

    const pageContextInit = {
      urlOriginal: url,
    }

    const pageContext = await renderPage(pageContextInit)
    const { httpResponse } = pageContext

    if (!httpResponse) {
      return response.status(200).end()
    }

    const { body, statusCode, headers } = httpResponse
    headers.forEach(([name, value]) => response.setHeader(name, value))

    if (statusCode >= 500) {
      const vikeFallback = typeof body === 'string' && body.includes('This HTML was generated by Vike')
      const renderError = pageContext?.errorWhileRendering

      response.setHeader('x-ssr-diagnostic', vikeFallback ? 'vike-fallback-500' : 'generic-500')
      response.setHeader('x-ssr-has-render-error', renderError ? '1' : '0')

      if (renderError) {
        const message = String(renderError?.message || '').slice(0, 200)
        response.setHeader('x-ssr-error-message', message || 'unknown')
        console.error('[SSR_RENDER_ERROR]', {
          url,
          message,
          stack: renderError?.stack,
        })
      }
    }

    return response.status(statusCode).send(body)
  } catch (error) {
    console.error('[SSR_HANDLER_ERROR]', error)
    response.setHeader('x-ssr-diagnostic', 'handler-catch')
    response.setHeader('Content-Type', 'text/html; charset=utf-8')
    return response.status(500).send('<p>An error occurred.</p>')
  }
}
