export default async function handler(request, response) {
  try {
    const { renderPage } = await import('vike/server')
    const { url } = request

    const pageContextInit = {
      urlOriginal: url,
    }

    const pageContext = await renderPage(pageContextInit)
    const { httpResponse } = pageContext

    if (!httpResponse) {
      return response.status(200).end()
    }

    const { body, statusCode, headers } = httpResponse
    // Achado (Lighthouse contra produção real): Vike define Cache-Control: no-store por
    // padrão em toda resposta SSR (seguro-por-padrão para conteúdo potencialmente
    // personalizado). Este app não personaliza o HTML gerado no servidor — o renderer só usa
    // pageContext.urlOriginal (confirmado em renderer/+onRenderHtml.tsx; nenhum cookie/header
    // de sessão é lido durante o SSR, auth é 100% client-side pós-hidratação) — então dois
    // visitantes pedindo a mesma URL recebem o mesmo HTML, sempre. "no-store" bloqueia o
    // back/forward cache do navegador (toda navegação de voltar exige recarregar do zero) e
    // sobrepõe silenciosamente a política já declarada para este mesmo domínio em
    // vercel.json ("s-maxage=3600, stale-while-revalidate=86400"). Não repetimos o valor
    // aqui — só deixamos de forçar o "no-store" do Vike em respostas de sucesso, para a
    // política já declarada no vercel.json valer.
    for (const [name, value] of headers) {
      if (name.toLowerCase() === 'cache-control' && statusCode < 400 && value.includes('no-store')) {
        continue
      }
      response.setHeader(name, value)
    }

    if (statusCode >= 500) {
      const vikeFallback = typeof body === 'string' && body.includes('This HTML was generated by Vike')
      const renderError = pageContext?.errorWhileRendering

      response.setHeader('x-ssr-diagnostic', vikeFallback ? 'vike-fallback-500' : 'generic-500')
      response.setHeader('x-ssr-has-render-error', renderError ? '1' : '0')

      if (renderError) {
        const message = String(renderError?.message || '').slice(0, 200)
        response.setHeader('x-ssr-error-message', message || 'unknown')
        console.error('[SSR_RENDER_ERROR]', {
          url,
          message,
          stack: renderError?.stack,
        })
      }
    }

    return response.status(statusCode).send(body)
  } catch (error) {
    console.error('[SSR_HANDLER_ERROR]', error)
    response.setHeader('x-ssr-diagnostic', 'handler-catch')
    response.setHeader('Content-Type', 'text/html; charset=utf-8')
    return response.status(500).send('<p>An error occurred.</p>')
  }
}
